### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mapaxe** [Mapaxe/angular2-playground#1]
- [x]  Integrar angular2 con NPM
- [x] Generar Servicio y Clase de la estructura de datos Alumno
- [x]  Generar Vista de Lista de Alumnos
- [x]  Generar Vista de Detalle de Alumno
- [x]  Generar Vista de Editar de Alumno
- [x]  Generar Vista de Agregar de Alumno
- [x]  Generar Vista de Eliminar de Alumno
- [x]  Generar Vista de Editar de Alumnos

La estructura de Datos debera ser un json:

``` json
[{
    "id": "1",
    "nombre": "Juan",
    "primer_apellido": "Lopez",
    "segundo_apellido": "Perez",
    "fecha_nacimiento": "1/1/1988"
}]
```
